services:
  notebook:
    image: jupyter/scipy-notebook
    container_name: con-lab
    
    ports:
      - "8999:8888"
    
    volumes:
      - ./work:/home/jovyan/work
    # 最後にjupyterLabに接続するためのコマンドを実行する。パスワード無し
    command: start-notebook.sh --NotebookApp.token=''

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata: