services:
  notebook:
    image: jupyter/scipy-notebook
    container_name: laboc
    
    ports:
      - "8999:8888"
    
    volumes:
      - ./work:/home/jovyan/work
    # 最後にjupyterLabに接続するためのコマンドを実行する。パスワード無し
    command: start-notebook.sh --NotebookApp.token=''
    depends_on:
      - db
      

  db:
    image: postgres:latest
    container_name: pgc
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adc
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pgdata: